early_stopping_min_delta: 0.002
early_stopping_patience: 5
epochs: 250
learning_rate: 0.015
optimizer: Adam
plateau_cooldown: 0
plateau_min_delta: 0.001
plateau_patience: 2
robustness: IRd
weight_decay: 0.0005
